config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  get  'dashboard/fb_posts'
  get 'dashboard/likes'
  get 'dashboard/comments'
  get 'dashboard/tweet_details'
  get 'dashboard/tweet_text'
  get 'dashboard/followers_twitter'

    root to: 'dashboard#index'
    

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  layout 'dashboard'
  @@page = FbGraph::Page.fetch('113866005332897',:access_token => "661208107330805|5IrEoXCReFDFSxeB1j9Zju_XNOI")
  def index
    @total_likes = @@page.raw_attributes[:likes]
    @@page_id = @@page.identifier
    @@page_link = @@page.raw_attributes[:link]
    @post_count = @@page.posts.count
    @talking_about = @@page.raw_attributes[:talking_about_count]
  end

  def fb_posts
    @posts = @@page.posts
  end

  def likes
    post_identifier =  params[:postidentifier]
    posts = @@page.posts
    posts.each do |i|
      if i.identifier == post_identifier
        puts i.identifier
        puts post_identifier
        @liked_post = i
        @likes = @liked_post.likes
      end
    end

  end

  def comments
    @@page = FbGraph::Page.fetch('113866005332897',:access_token => "661208107330805|5IrEoXCReFDFSxeB1j9Zju_XNOI")
    post_identifier =  params[:postidentifier]
    posts = @@page.posts
    posts.each do |i|
      if i.identifier == post_identifier
        puts i.identifier
        puts post_identifier
        @commented_post = i
        @comments = @commented_post.comments
      end
    end
  end

  def collect_with_max_id(collection=[], max_id=nil, &block)
    response = yield(max_id)
    collection += response
    response.empty? ? collection.flatten : collect_with_max_id(collection, response.last.id - 1, &block)
  end

  def $client.get_all_tweets(user)
    collect_with_max_id do |max_id|
      options = {count: 200, include_rts: true}
      options[:max_id] = max_id unless max_id.nil?
      user_timeline(user, options)
    end
  end

  def tweet_details
    begin
      @count = $client.get_all_tweets("Maruti_Corp").count
    rescue Exception => e
      render plain: "Please try Again after some time"
    end
  end

  def tweet_text
    begin
      @ids = $client.get_all_tweets("Maruti_Corp").take(10)
    rescue Exception => e
      render plain: "Please try Again after some time"
    end
  end

  def followers_twitter
    @obj3=$client.followers("Maruti_Corp").take(10)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def post(post)
    post_type = post.type
    puts "post type is #{post_type} for #{post}"
    case post_type
    when "photo"
      post_details = post.link
      likes_count = post.likes.count
      comments_count = post.comments.count
    when "status"
      post_details = post.story
      likes_count = post.likes.count
      comments_count = 0
    else
    post_details = 0
    likes_count = 0
    comments_count = 0
    end
    [post_type,post_details,likes_count,comments_count]
  end

  def favorite(tweet_id)
   obj1=$client.status(tweet_id)
   obj1.favorite_count
end
def retweets(tweet_id)
   obj2=$client.status(tweet_id)
   obj2.retweet_count
end
def follower_details(follower)
   [follower.id,follower.screen_name]
end

end

app/views/dashboard/comments.html.erb
<%= content_for :header do %>
<%= javascript_include_tag "dataTables.bootstrap","posts" %>
<%end%>
	
	
<div class="table-responsive">
	<h2 class="page-header">Comment History</h2>
    <div style="float:right"><%=link_to "Home",root_path,html_options = {:class => "btn btn-primary"}%></div>
    <br>
    <br>
	<table class="table table-striped table-bordered" id="posts_table">
		<thead>
			<tr>
				<th>Commented By</th>
				<th>Comment</th>
				<th>Profile Link</th>
				<th>Total Likes</th>
			</tr>
		</thead>
		<tbody>
			<% unless @comments.nil?%>
	         <%@comments.each do |i|%>
			<tr>
				<td><%=i.raw_attributes[:from][:name]%></td>
				<td><%=i.raw_attributes[:message]%>
				<%profile_id = i.raw_attributes[:from][:id]%>
				<%url="https://www.facebook.com/"%>
				<%url << profile_id%>
				<td><a href=<%=url%> target = "_blank"><%=url%></td>
				<td><%=i.raw_attributes[:like_count]%></td>
			</tr>
			<% end %>
			<% end %>
		</tbody>
	</table>
</div>

app/views/dashboard/fb_posts.html.erb
<%= content_for :header do %>
<%= javascript_include_tag "dataTables.bootstrap","posts" %>
<%end%>
<div class="table-responsive">
	<h2 class="page-header">Facebook Posts</h2>
	<div style="float:right">
		<%= link_to "Home",root_path,html_options = {:class => "btn btn-primary"}%>
	</div>
	<br>
	<br>

	<table class="table table-striped table-bordered" id="posts_table">
		<thead>
			<tr>
				<th>Post Type</th>
				<th>Post</th>
				<th>Total Likes</th>
				<th>Total Comments</th>
			</tr>
		</thead>
		<tbody>
			<%@posts.each do |i|%>
			<tr>
				<td><%= post(i)[0]%></td>
				<td><a href=<%= post(i)[1]%> target= "_blank"><%= post(i)[1]%></a></td>
				<% a=post(i)[2]%>
				<td> <%= link_to a,dashboard_likes_path(:postidentifier => i.identifier), target: '_blank'%> </td>
				<% b=post(i)[3]%>
				<td> <%= link_to b,dashboard_comments_path(:postidentifier => i.identifier), target: '_blank'%> </td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/dashboard/followers_twitter.html.erb
<%= content_for :header do %>
<%= javascript_include_tag "dataTables.bootstrap","posts" %>
<%end%>
<div class="table-responsive">
	<h2 class="page-header">Tweet Details</h2>
	<div style="float:right">
		<%= link_to "Home",root_path,html_options = {:class => "btn btn-primary"}%>
	</div>
	<br>
	<br>

	<table class="table table-striped table-bordered" id="posts_table">
		<thead>
			<tr>
				<th>Followers ID</th>
				<th>Screen Name</th>
				
			</tr>
		</thead>
		<tbody>
			<%@obj3.each do |f|%>
			<tr>
				
				<td><%= follower_details(f)[0] %></td>
				<td><%= follower_details(f)[1] %></td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/dashboard/index.html.erb
<script>
$(function () {
    $('#container').highcharts({
        title: {
            text: 'Monthly Facebook Like Statistics',
            x: -20 //center
        },
        xAxis: {
            categories: ['Aug/14', 'Sep/14','Oct/14','Nov/14','Dec/14','Jan/15','Feb/15']
        },
        yAxis: {
            title: {
                text: 'Likes'
            },
            plotLines: [{
                value: 0,
                width: 1,
                color: '#808080'
            }]
        },
        tooltip: {
        },
        credits: {
        	enabled: false
        },
        legend: {
            layout: 'vertical',
            align: 'right',
            verticalAlign: 'middle',
            borderWidth: 0
        },
        series: [{
            name: 'Likes',
            data: [1256100, 1256150, 1256200, 1256250, 1256250, 1256300, 1256616]
        }]
    });
});
</script>
<div id ="social">
	<ul>
		<li>
			<a href="#"><i class="fa fa-facebook active"></i></a>
		</li>
		<li>
			<a href="/dashboard/tweet_details/"><i class="fa fa-twitter"></i></a>
		</li>
		<li>
			<a href="http://linkedin.com/"><i class="fa fa-linkedin"></i></a>
		</li>
		<li>
			<a href="http://plus.google.com/"><i class="fa fa-google-plus"></i> </a>
		</li>
	</ul>
</div>
<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header"> Facebook <small>Dashboard</small></h1>
		<ol class="breadcrumb">
			<li class="active">
				<i class="fa fa-dashboard"></i> Dashboard
			</li>
		</ol>
	</div>
</div>
<div class="row">
	<div class="col-lg-3 col-md-6">
		<div class="panel panel-red">
			<div class="panel-heading">
				<div class="row">
					<div class="col-xs-3">
						<i class="fa fa-support fa-5x"></i>
					</div>
					<div class="col-xs-9 text-right">
						<div class="huge">
							<%= @page_id%>
						</div>
						<div>
							Page ID
						</div>
					</div>
				</div>
			</div>

			<div class="panel-footer">
				<span class="pull-left"><%= link_to "View Details","https://www.facebook.com/MarutiSuzukiWayOfLife" , target: '_blank'%></span>
				<a href="https://www.facebook.com/MarutiSuzukiWayOfLife" target="_blank"> <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span> <div class="clearfix"></div>
			</div>
			</a>
		</div>
	</div>
	<div class="col-lg-3 col-md-6">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<div class="row">
					<div class="col-xs-3">
						<i class="fa fa-thumbs-o-up fa-5x"></i>
					</div>
					<div class="col-xs-9 text-right">
						<div class="huge">
							<%= @total_likes%>
						</div>
						<div>
							Total Likes!
						</div>
					</div>
				</div>
			</div>

			<div class="panel-footer">
				<span class="pull-left"><%= link_to "View Details","https://www.facebook.com/plugins/fan.php?connections=100&id=136872339701549", target: '_blank'%></span>
				<a href="https://www.facebook.com/plugins/fan.php?connections=100&id=249343554283" target="_blank"> <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span> <div class="clearfix"></div>
			</div>
			</a>
		</div>
	</div>
	<div class="col-lg-3 col-md-6">
		<div class="panel panel-green">
			<div class="panel-heading">
				<div class="row">
					<div class="col-xs-3">
						<i class="fa fa-comments fa-5x"></i>
					</div>
					<div class="col-xs-9 text-right">
						<div class="huge">
							<%= @post_count%>
						</div>
						<div>
							Total Posts!
						</div>
					</div>
				</div>
			</div>

			<div class="panel-footer">
				<span class="pull-left"><%= link_to "View Details",dashboard_fb_posts_path, target: '_blank'%></span>
				<a href="/dashboard/fb_posts" target="_blank"> <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span> <div class="clearfix"></div>
			</div>
			</a>
		</div>
	</div>
	<div class="col-lg-3 col-md-6">
		<div class="panel panel-yellow">
			<div class="panel-heading">
				<div class="row">
					<div class="col-xs-3">
						<i class="fa fa-heart fa-5x"></i>
					</div>
					<div class="col-xs-9 text-right">
						<div class="huge">
							<%= @talking_about%>
						</div>
						<div>
							People Talking About
						</div>
					</div>
				</div>
			</div>
			<a href="#">
			<div class="panel-footer">
				<span class="pull-left">View Details</span>
				<span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
				<div class="clearfix"></div>
			</div> </a>
		</div>
	</div>
</div>
<div id="container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>

app/views/dashboard/likes.html.erb
<%= content_for :header do %>
<%= javascript_include_tag "dataTables.bootstrap","posts" %>
<%end%>
	
	
<div class="table-responsive">
	<h2 class="page-header">Facebook Like History</h2>
	<div style="float:right"><%=link_to "Home",root_path,html_options = {:class => "btn btn-primary"}%></div>
	<br>
	<br>
	<table class="table table-striped table-bordered" id="posts_table">
		<thead>
			<tr>
				<th>Liked By</th>
				<th>Profile Link</th>
			</tr>
		</thead>
		<tbody>
			<% unless @likes.nil?%>
	         <%@likes.each do |i|%>
			<tr>
				<td><%=i.raw_attributes[:name]%></td></td>
				<%profile_id = i.raw_attributes[:id]%>
				<%url="https://www.facebook.com/"%>
				<%url << profile_id%>
				<td><a href=<%=url%> target ="_blank"><%=url%></td>
			</tr>
			<% end %>
			<% end %>
		</tbody>
	</table>
</div>

app/views/dashboard/tweet_by.html.erb
<%= content_for :header do %>
<%= javascript_include_tag "dataTables.bootstrap","posts" %>
<%end%>
<div class="table-responsive">
	<h2 class="page-header">Tweet Details</h2>
	<div style="float:right">
		<%= link_to "Home",root_path,html_options = {:class => "btn btn-primary"}%>
	</div>
	<br>
	<br>

	<table class="table table-striped table-bordered" id="posts_table">
		<thead>
			<tr>
				<th>Tweeted By</th>
								
				
			</tr>
		</thead>
		<tbody>
			<%obj3.each do |i|%>
			<tr>
				
				<td><%= retweetsby(i.id) %></td>
				
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/dashboard/tweet_details.html.erb
<script>
$(function () {
    $('#container').highcharts({
        title: {
            text: 'Monthly Followers Statistics',
            x: -20 //center
        },
        xAxis: {
            categories: ['Aug/14', 'Sep/14','Oct/14','Nov/14','Dec/14','Jan/15','Feb/15']
        },
        yAxis: {
            title: {
                text: 'Followers'
            },
            plotLines: [{
                value: 0,
                width: 1,
                color: '#808080'
            }]
        },
        tooltip: {
        },
        credits: {
        	enabled: false
        },
        legend: {
            layout: 'vertical',
            align: 'right',
            verticalAlign: 'middle',
            borderWidth: 0
        },
        series: [{
            name: 'Followers',
            data: [42113, 42325, 42511, 42640, 42905, 43072, 43175]
        }]
    });
});
</script>
<div id ="social">
	<ul>
		<li>
			<a href="/dashboard/index"><i class="fa fa-facebook "></i></a>
		</li>
		<li>
			<a href="/dashboard/tweet_details/"><i class="fa fa-twitter active"></i></a>
		</li>
		<li>
			<a href="http://linkedin.com/"><i class="fa fa-linkedin"></i></a>
		</li>
		<li>
			<a href="http://plus.google.com/"><i class="fa fa-google-plus"></i> </a>
		</li>
	</ul>
</div>
<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header"> Twitter <small>Dashboard</small></h1>
		<ol class="breadcrumb">
			<li class="active">
				<i class="fa fa-dashboard"></i> Dashboard
			</li>
		</ol>
	</div>
</div>
<div class="row">
	<div class="col-lg-3 col-md-6">
		<div class="panel panel-red">
			<div class="panel-heading">
				<div class="row">
					<div class="col-xs-3">
						<i class="fa fa-support fa-5x"></i>
					</div>
					<div class="col-xs-9 text-right">
						<div class>
							@Maruti_Corp
						</div>
						<div>
							Twitter Handle
						</div>
					</div>
				</div>
			</div>

			<div class="panel-footer">
				<span class="pull-left"><%= link_to "View Details","https://twitter.com/Maruti_Corp" , target: '_blank'%></span>
				<a href="https://twitter.com/Maruti_Corp" target="_blank"> <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span> <div class="clearfix"></div>
			</div>
			</a>
		</div>
	</div>
	<div class="col-lg-3 col-md-6">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<div class="row">
					<div class="col-xs-3">
						<i class="fa fa-thumbs-o-up fa-5x"></i>
					</div>
					<div class="col-xs-9 text-right">
						<div class="huge">
							11271
						</div>
						<div>
							Followers Count!
						</div>
					</div>
				</div>
			</div>

			<div class="panel-footer">
				<span class="pull-left"><%= link_to "View Details",dashboard_followers_twitter_path, target: '_blank'%></span>
				<a href="/dashboard/followers_twitter" target="_blank"> <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span> <div class="clearfix"></div>
			</div>
			</a>
		</div>
	</div>
	<div class="col-lg-3 col-md-6">
		<div class="panel panel-green">
			<div class="panel-heading">
				<div class="row">
					<div class="col-xs-3">
						<i class="fa fa-twitter fa-5x"></i>
					</div>
					<div class="col-xs-9 text-right">
						<div class="huge">
							<%= @count%>
						</div>
						<div>
							Total Tweets!
						</div>
					</div>
				</div>
			</div>

			<div class="panel-footer">
				<span class="pull-left"><%= link_to "View Details", dashboard_tweet_text_path, target: '_blank'%></span>
				<a href="/dashboard/tweet_text" target="_blank"> <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span> <div class="clearfix"></div>
			</div>
			</a>
		</div>
	</div>
	<div class="col-lg-3 col-md-6">
		<div class="panel panel-yellow">
			<div class="panel-heading">
				<div class="row">
					<div class="col-xs-3">
						<i class="fa fa-heart fa-5x"></i>
					</div>
					<div class="col-xs-9 text-right">
						<div class="huge">
							120
						</div>
						<div>
							Following!
						</div>
					</div>
				</div>
			</div>
			<a href="#">
			<div class="panel-footer">
				<span class="pull-left">View Details</span>
				<span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
				<div class="clearfix"></div>
			</div> </a>
		</div>
	</div>
</div>
<div id="container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>

app/views/dashboard/tweet_text.html.erb
<%= content_for :header do %>
<%= javascript_include_tag "dataTables.bootstrap","posts" %>
<%end%>
<div class="table-responsive">
	<h2 class="page-header">Tweet Details</h2>
	<div style="float:right">
		<%= link_to "Home",root_path,html_options = {:class => "btn btn-primary"}%>
	</div>
	<br>
	<br>

	<table class="table table-striped table-bordered" id="posts_table">
		<thead>
			<tr>
				<th>Tweet Id</th>
				<th>Tweets</th>
				<th>Favorites Count</th>
				<th>Retweets Count</th>
				
			</tr>
		</thead>
		<tbody>
			<%@ids.each do |i|%>
			<tr>
				<td><%= i.id%></td>
				<td><%= i.text%></td>
				<td><%= favorite(i.id) %></td>
				<td><%= retweets(i.id) %></td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RelianceMutualSocialMediaAnalytics</title>
  <%= stylesheet_link_tag   'application','font-awesome','bootstrap.min','font-awesome.min'  %>
  <%= javascript_include_tag 'jquery', 'jquery_ujs','jquery.dataTables.min'%>
  <%= yield :header%>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container-fluid">
			<div class="row">
				<div class="col-sm-3 col-md-2 sidebar">
				</div>
				<div class="reliance col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
					<%= yield %>
				</div>
			</div>

		</div>
</body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MarutiSocialMedia</title>
  <%= stylesheet_link_tag  'application','bootstrap.min','font-awesome.min','dashboard','dataTables.bootstrap'%>
  <%= javascript_include_tag 'jquery', 'jquery_ujs','jquery.dataTables.min','https://code.highcharts.com/highcharts.js'%>
  <%= yield :header%>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container-fluid">
			<div class="row">
				<div class="col-sm-3 col-md-2 sidebar">
				</div>
				<div class="reliance col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
					<div id="wrapper">
						<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<div id="logo" style="padding-left: 10px;margin-top: 10px">
			<%= link_to image_tag("logo.png"), root_path %>
			</div>
		</div>
		<!-- Top Menu Items -->
		<ul class="nav navbar-right top-nav">
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> Admin <b class="caret"></b></a>
				<ul class="dropdown-menu">
					<li>
						<a href="#"><i class="fa fa-fw fa-user"></i> Profile</a>
					</li>
					<li>
						<a href="#"><i class="fa fa-fw fa-envelope"></i> Inbox</a>
					</li>
					<li>
						<a href="#"><i class="fa fa-fw fa-gear"></i> Settings</a>
					</li>
					<li class="divider"></li>
					<li>
						<a href="#"><i class="fa fa-fw fa-power-off"></i> Log Out</a>
					</li>
				</ul>
			</li>
		</ul>
		<!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
		<div class="collapse navbar-collapse navbar-ex1-collapse">
			<ul class="nav navbar-nav side-nav">
				<li class="active">
					<a href="#"><i class="fa fa-fw fa-dashboard"></i> Social Media</a>
				</li>
				<li class="<%= @app_store_class %>">
					<a href="#"><i class="fa fa-mobile fa-1.5x"></i> App Store</a>
				</li>
				<li class="<%= @website_class %>">
					<a href="#"><i class="fa fa-laptop"></i> Website</a>
				</li>
				<li>
					<a href="#"><i class="fa fa-fw fa-edit"></i> Manage & Publish</a>
				</li>
				<li>
					<a href="#"><i class="fa fa-bar-chart"></i>Charts & Graphs</a>
				</li>
			</ul>
		</div>
		<!-- /.navbar-collapse -->
	</nav>
	<div id="page-wrapper">
		<div class="container-fluid">
			<%=yield%>
		</div>
		</div>
					</div>
				</div>
			</div>

		</div>
</body>
</html>